### ISSUE TITLE
godot 1.1

### ISSUE THREAD

**Issue by mohaalak** [bibby/gd-rpc#1]
it raise an error in rpg.gd in godot 1.1
var RPC = preload("rpc.gd");

when I change it to get_script() it will raise another error saying
cannot access self without instance

**Comment by bibby** [comment]
Thanks. gd-rpc was quickly made for a much earlier version of godot. Since then, I haven't been following the project. Perhaps one of the forks have worked around this.

**Comment by Andi-K** [comment]
The factory don't work but there is no need for it.
A fast test shows that everything else still works with GoDot 2.0 Alpha. :+1:
